package surveyApp;

import javax.swing.ButtonGroup;
import javax.swing.AbstractButton;
import java.util.Enumeration;
import java.util.List;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

public class FillOutForm extends javax.swing.JFrame {

    // Declare radio button groups
    private ButtonGroup groupEat;
    private ButtonGroup groupMovie;
    private ButtonGroup groupTV;
    private ButtonGroup groupRadio;

    /**
     * Creates new form FillOutForm
     */
    public FillOutForm() {
        initComponents();

        // Group for "Do you like to eat out?"
        groupEat = new ButtonGroup();
        groupEat.add(radStrAgrEat);
        groupEat.add(radAgrEat);
        groupEat.add(radNeutEat);
        groupEat.add(radDisAgrEat);
        groupEat.add(radStrDisAgrEat);

// Group for "Do you like to watch movies?"
        groupMovie = new ButtonGroup();
        groupMovie.add(radStrAgrMovie);
        groupMovie.add(radAgrMovie);
        groupMovie.add(radNeutMovie);
        groupMovie.add(radDisAgrMovie);
        groupMovie.add(radStrDisAgrMovie);

// Group for "Do you like to watch TV?"
        groupTV = new ButtonGroup();
        groupTV.add(radStrAgrTV);
        groupTV.add(radAgrTV);
        groupTV.add(radNeutTV);
        groupTV.add(radDisAgrTV);
        groupTV.add(radStrDisAgrTV);

// Group for "Do you like to listen to the radio?"
        groupRadio = new ButtonGroup();
        groupRadio.add(radStrAgrRadio);
        groupRadio.add(radAgrRadio);
        groupRadio.add(radNeutRadio);
        groupRadio.add(radDisAgrRadio);
        groupRadio.add(radStrDisAgrRadio);

    }

    private int getSelectedRating(ButtonGroup group) {
        int value = -1;
        Enumeration<AbstractButton> buttons = group.getElements();
        int i = 1;
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                value = i;
                break;
            }
            i++;
        }
        return value;
    }

    private void clearForm() {
        // Clear text fields
        jTextField1.setText(""); // Full Name
        jTextField2.setText(""); // Email
        jTextField4.setText(""); // Contact

        //Clear date picker
        dateChooserDob.setDate(null);

        // Uncheck food checkboxes
        chkPizza.setSelected(false);
        chkPasta.setSelected(false);
        chkPapWors.setSelected(false);
        chkOther.setSelected(false);

        // Clear radio button selections
        groupEat.clearSelection();
        groupMovie.clearSelection();
        groupTV.clearSelection();
        groupRadio.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlMovie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radStrAgrMovie = new javax.swing.JRadioButton();
        radAgrMovie = new javax.swing.JRadioButton();
        radNeutMovie = new javax.swing.JRadioButton();
        radDisAgrMovie = new javax.swing.JRadioButton();
        radStrDisAgrMovie = new javax.swing.JRadioButton();
        pnlRadio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radStrAgrRadio = new javax.swing.JRadioButton();
        radAgrRadio = new javax.swing.JRadioButton();
        radNeutRadio = new javax.swing.JRadioButton();
        radDisAgrRadio = new javax.swing.JRadioButton();
        radStrDisAgrRadio = new javax.swing.JRadioButton();
        pnlEat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radStrAgrEat = new javax.swing.JRadioButton();
        radAgrEat = new javax.swing.JRadioButton();
        radNeutEat = new javax.swing.JRadioButton();
        radDisAgrEat = new javax.swing.JRadioButton();
        radStrDisAgrEat = new javax.swing.JRadioButton();
        pnlTV = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radStrAgrTV = new javax.swing.JRadioButton();
        radAgrTV = new javax.swing.JRadioButton();
        radNeutTV = new javax.swing.JRadioButton();
        radDisAgrTV = new javax.swing.JRadioButton();
        radStrDisAgrTV = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkPizza = new javax.swing.JCheckBox();
        chkPasta = new javax.swing.JCheckBox();
        chkPapWors = new javax.swing.JCheckBox();
        chkOther = new javax.swing.JCheckBox();
        btnFillOut = new javax.swing.JButton();
        btnViewResults = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        dateChooserDob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Strongly Agree", "Agree", "Neutral", "Disagree", "Strongly Disagree"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("I like to watch movies");

        javax.swing.GroupLayout pnlMovieLayout = new javax.swing.GroupLayout(pnlMovie);
        pnlMovie.setLayout(pnlMovieLayout);
        pnlMovieLayout.setHorizontalGroup(
            pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(radStrAgrMovie)
                .addGap(118, 118, 118)
                .addComponent(radAgrMovie)
                .addGap(108, 108, 108)
                .addComponent(radNeutMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radDisAgrMovie)
                .addGap(103, 103, 103)
                .addComponent(radStrDisAgrMovie)
                .addGap(57, 57, 57))
        );
        pnlMovieLayout.setVerticalGroup(
            pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAgrMovie)
                    .addComponent(radNeutMovie)
                    .addComponent(radDisAgrMovie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radStrDisAgrMovie)
                    .addComponent(radStrAgrMovie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel2.setText("I like to listen to radio");

        javax.swing.GroupLayout pnlRadioLayout = new javax.swing.GroupLayout(pnlRadio);
        pnlRadio.setLayout(pnlRadioLayout);
        pnlRadioLayout.setHorizontalGroup(
            pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(radStrAgrRadio)
                .addGap(121, 121, 121)
                .addComponent(radAgrRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(radNeutRadio)
                .addGap(117, 117, 117)
                .addComponent(radDisAgrRadio)
                .addGap(106, 106, 106)
                .addComponent(radStrDisAgrRadio)
                .addGap(53, 53, 53))
        );
        pnlRadioLayout.setVerticalGroup(
            pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radDisAgrRadio)
                    .addGroup(pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radStrDisAgrRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radStrAgrRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radAgrRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radNeutRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel3.setText("I like to eat out");

        javax.swing.GroupLayout pnlEatLayout = new javax.swing.GroupLayout(pnlEat);
        pnlEat.setLayout(pnlEatLayout);
        pnlEatLayout.setHorizontalGroup(
            pnlEatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEatLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(radStrAgrEat)
                .addGap(122, 122, 122)
                .addComponent(radAgrEat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radNeutEat)
                .addGap(117, 117, 117)
                .addComponent(radDisAgrEat)
                .addGap(105, 105, 105)
                .addComponent(radStrDisAgrEat)
                .addGap(52, 52, 52))
        );
        pnlEatLayout.setVerticalGroup(
            pnlEatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radStrAgrEat)
                        .addComponent(jLabel3)
                        .addComponent(radAgrEat))
                    .addGroup(pnlEatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radNeutEat)
                        .addComponent(radStrDisAgrEat)
                        .addComponent(radDisAgrEat)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel5.setText("I like to watch TV");

        javax.swing.GroupLayout pnlTVLayout = new javax.swing.GroupLayout(pnlTV);
        pnlTV.setLayout(pnlTVLayout);
        pnlTVLayout.setHorizontalGroup(
            pnlTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTVLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(radStrAgrTV)
                .addGap(123, 123, 123)
                .addComponent(radAgrTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radNeutTV)
                .addGap(117, 117, 117)
                .addComponent(radDisAgrTV)
                .addGap(107, 107, 107)
                .addComponent(radStrDisAgrTV)
                .addGap(49, 49, 49))
        );
        pnlTVLayout.setVerticalGroup(
            pnlTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radNeutTV)
                        .addGroup(pnlTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radAgrTV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radDisAgrTV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)))
                    .addComponent(radStrAgrTV)
                    .addComponent(radStrDisAgrTV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlMovie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Please rate your level of agreement on a scale of 1 to 5, with 1 being \"strongly agree\" and 5 being \"strongly disagree\".");

        jLabel6.setText("What is your favorite food?");

        chkPizza.setText("Pizza");
        chkPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPizzaActionPerformed(evt);
            }
        });

        chkPasta.setText("Pasta");

        chkPapWors.setText("Pap and Wors");

        chkOther.setText("Other");

        btnFillOut.setText("Fill OUT SURVEY");

        btnViewResults.setText("VIEW SURVEY RESULTS");
        btnViewResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResultsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("_Surveys");

        jLabel8.setText("Personal Details:");

        jLabel9.setText("Full Names");

        jLabel10.setText("Email");

        jLabel11.setText("Date of Birth");

        jLabel12.setText("Contact Number");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkPasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkPapWors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkOther)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFillOut, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnViewResults)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChooserDob, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFillOut)
                        .addComponent(btnViewResults))
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkPizza)
                    .addComponent(chkPasta)
                    .addComponent(chkPapWors)
                    .addComponent(chkOther))
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPizzaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        // Get user input
        String name = jTextField1.getText().trim();
        String email = jTextField2.getText().trim();
        String contact = jTextField4.getText().trim();

        // Basic validation
        if (name.isEmpty() || email.isEmpty() || contact.isEmpty() || dateChooserDob.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please complete all personal details.");
            return;
        }

        LocalDate dobDate;
        int age;

        try {
            Date selectedDate = dateChooserDob.getDate();
            dobDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            age = LocalDate.now().getYear() - dobDate.getYear();

            if (age < 5 || age > 120) {
                JOptionPane.showMessageDialog(this, "Age must be between 5 and 120.");
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Date of Birth. Please select a valid date.");
            return;
        }

        // Favorite foods
        List<String> selectedFoods = new ArrayList<>();
        if (chkPizza.isSelected()) {
            selectedFoods.add("Pizza");
        }
        if (chkPasta.isSelected()) {
            selectedFoods.add("Pasta");
        }
        if (chkPapWors.isSelected()) {
            selectedFoods.add("Pap and Wors");
        }
        if (chkOther.isSelected()) {
            selectedFoods.add("Other");
        }

        // Ratings
        int eatOut = getSelectedRating(groupEat);
        int watchMovies = getSelectedRating(groupMovie);
        int watchTV = getSelectedRating(groupTV);
        int listenRadio = getSelectedRating(groupRadio);

        if (eatOut == -1 || watchMovies == -1 || watchTV == -1 || listenRadio == -1) {
            JOptionPane.showMessageDialog(this, "Please provide a rating for each lifestyle question.");
            return;
        }

        // Save to DB
        surveyDB_connector dao = new surveyDB_connector();
        dao.saveSurvey(name, email, age, dobDate, selectedFoods, eatOut, watchMovies, watchTV, listenRadio);

        JOptionPane.showMessageDialog(this, "Survey submitted successfully!");
        clearForm();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResultsActionPerformed
        ViewSurveyForm resultsForm = new ViewSurveyForm();
        resultsForm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillOutForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillOutForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillOutForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillOutForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillOutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFillOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewResults;
    private javax.swing.JCheckBox chkOther;
    private javax.swing.JCheckBox chkPapWors;
    private javax.swing.JCheckBox chkPasta;
    private javax.swing.JCheckBox chkPizza;
    private com.toedter.calendar.JDateChooser dateChooserDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel pnlEat;
    private javax.swing.JPanel pnlMovie;
    private javax.swing.JPanel pnlRadio;
    private javax.swing.JPanel pnlTV;
    private javax.swing.JRadioButton radAgrEat;
    private javax.swing.JRadioButton radAgrMovie;
    private javax.swing.JRadioButton radAgrRadio;
    private javax.swing.JRadioButton radAgrTV;
    private javax.swing.JRadioButton radDisAgrEat;
    private javax.swing.JRadioButton radDisAgrMovie;
    private javax.swing.JRadioButton radDisAgrRadio;
    private javax.swing.JRadioButton radDisAgrTV;
    private javax.swing.JRadioButton radNeutEat;
    private javax.swing.JRadioButton radNeutMovie;
    private javax.swing.JRadioButton radNeutRadio;
    private javax.swing.JRadioButton radNeutTV;
    private javax.swing.JRadioButton radStrAgrEat;
    private javax.swing.JRadioButton radStrAgrMovie;
    private javax.swing.JRadioButton radStrAgrRadio;
    private javax.swing.JRadioButton radStrAgrTV;
    private javax.swing.JRadioButton radStrDisAgrEat;
    private javax.swing.JRadioButton radStrDisAgrMovie;
    private javax.swing.JRadioButton radStrDisAgrRadio;
    private javax.swing.JRadioButton radStrDisAgrTV;
    // End of variables declaration//GEN-END:variables
}
